services:
  backend:
    container_name: baguette-backend-test
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    env_file:
      - ./.env.backend
    environment:
      NODE_ENV: production
    ports:
      - "${BACKEND_TEST_PORT:-6315}:3000"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
