services:
  pgadmin:
    image: dpage/pgadmin4:9.7
    container_name: baguette-pgadmin
    env_file:
      - ./.env.pgadmin
    ports:
      - "${PGADMIN_PORT:-6316}:5050"
    volumes:
      - ./data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
