services:
  nginx:
    container_name: baguette-nginx-test
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    env_file:
      - ./.env.nginx
    ports:
      - "${NGINX_PORT:-6313}:80"
    volumes:
      - ./logs:/var/log/nginx
      - ./files/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ../website/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
