services:
  website:
    container_name: baguette-website-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      VITE_DEV_SERVER_PORT: ${WEBSITE_DEV_PORT:-5173}
    ports:
      - "${WEBSITE_DEV_PORT:-5173}:5173"
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - backend-network

networks:
  backend-network:
    external: true
